- graphene/contrib/django/views.py
More efforts to achieve Django 1.6 compatibility!
Graphene's Django views [uses Django JsonResponse object](https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/views.py#L3), which wasn't [introduced until Django 1.7.](https://docs.djangoproject.com/en/1.8/ref/request-response/#jsonresponse-objects)
Use HttpResponse instead of JsonResponse with JSON encoded data.  Also, tests that passed on master passed with this change.
> Django 1.6 compatibility for views

- graphene/contrib/django/views.py
- tests/contrib_django/test_views.py
The `GraphQLView` in contrib/django now also accepts content-type "application/graphql", for which it simply uses the request body as the query.
> added check for content-type "application/graphql" in django view

- examples/starwars_django/schema.py
- examples/starwars_relay/schema.py
- graphene/contrib/django/tests/test_query.py
- graphene/relay/fields.py
- graphene/relay/tests/test_query.py
This allows request_context (or any other ResolveInfo data) to be used while getting nodes.
For example, some data might need to be hidden based on the user's authorization; you would use info.request_context for this.
Fixes #34.
> Add the info parameter (ResolveInfo) to get_node() calls.

- quickstart.md
Running the example previously resulted in a `FutureWarning`.
```bash
…/graphene/core/fields.py:14: FutureWarning: Using StringField is not longer supported
cls.__name__), FutureWarning)
```
```
blinker==1.4
graphene==0.4.1.1
graphql-core==0.4.9
graphql-relay==0.3.3
six==1.10.0
wsgiref==0.1.2
```
> Update quickstart example

- docs/pages/docs/basic-types.md
This document is based on my reading of the tests.
Ideally, without reading the test, I attempted to create a custom type using normal means, and providing it as an argument again as normal means.
After lots of head scratching, I found the solution, but maybe the behaviour could be fixed at the library level so that the following works:
```python
class CustomArgumentObjectType(graphene.ObjectType):
field1 = graphene.String()
field2 = graphene.String()
```
And then:
```
graphene.Field(graphene.String(), to=CustomArgumentObjectType())
```
> Add documentation about using custom input object types as arguments

- graphene/contrib/django/converter.py
- graphene/contrib/django/tests/test_converter.py
No need for backwards compatibility because GenericIPAddressField exists in 1.6+
> Add support for GenericIPAddressField

- graphene/contrib/django/management/commands/graphql_schema.py
* Implement Django `./manage.py graphql_schema`
* Required to have 'graphene.django.contrib' in INSTALLED_APPS setting
* Introduces two new optional settings GRAPHENE_SCHEMA and
GRAPHENE_SCHEMA_OUTPUT
* GRAPHENE_SCHEMA for the Django app containing the schema
* GRAPHENE_SCHEMA_OUTPUT for the output file (defaults to schema.json)
* Use `./manage.py graphql_schema -h` for help in command line
* Also a handy solution for issue #3
> Implement Django command for dumping schema.json

- docs/pages/docs/introspection-schema.md
Documentation for the graphql_schema management command. Feel free to edit it to suit the other docs.
> Add Django graphql_schema command documentation

- docs/pages/docs/mutations.md
I believe the function listed in the tutorial is incorrect as mentioned in issue #76.  Changed it to match what's used in the Star Wars examples.
> Changed mutation documentation in reference to Issue #76

- graphene/relay/fields.py
- graphene/relay/tests/test_query.py
Hey, I found bug related to ```relay.NodeField('MyNode')``` behavior, which I assume should be exactly the same as using ```relay.NodeField(MyNode)```. Here is simple fix for that.
> Fixed NodeField object_type string name argument.

- graphene/core/classtypes/objecttype.py
- graphene/core/types/field.py
- graphene/core/types/tests/test_field.py
- graphene/utils/__init__.py
- graphene/utils/maybe_func.py
- graphene/utils/tests/test_maybe_func.py
As reflected in issue #101, this pull request adds the ability on `Field`s to support mapping to an `instance` attribute different than the field name, allowing the following to be possible:
```python
class ArtworkNode(DjangoNode):
url = graphene.String(source='get_absolute_url')
class Meta:
model = Artwork
filter_fields = ['id', 'title']
```
> Added source argument in Fields

- .coveragerc
- .travis.yml
- docs/config.toml
- docs/pages/docs/enums.md
- examples/starwars/schema.py
- graphene/__init__.py
- graphene/contrib/django/converter.py
- graphene/contrib/django/tests/test_converter.py
- graphene/contrib/django/types.py
- graphene/contrib/sqlalchemy/converter.py
- graphene/contrib/sqlalchemy/tests/test_converter.py
- graphene/core/__init__.py
- graphene/core/classtypes/__init__.py
- graphene/core/classtypes/enum.py
- graphene/core/classtypes/tests/test_enum.py
- graphene/utils/enum.py
- setup.cfg
- setup.py
Add Enum type and the corresponding `Django` and `SQLAlchemy` mappings when a Field/Column type have choices set up.
> Add Enum type

- docs/config.toml
- docs/pages/docs/django/authorization.md
This distills what I had to figure out to limit data access in Graphene. Since it's such a common task and isn't very intuitive, I figured it'd be a good idea to add some documentation.
> Add a doc on authorization in Django

- docs/pages/docs/basic-types.md
This tripped me up when trying to create a custom type. I also had to hunt in the source for the `Scalar` import so I added that as well.
> Add some clarifications to the custom Scalar type doc

- docs/pages/docs/mutations.md
The ok field in the example should be a Boolean since it is treated as one
> Fix incorrect type in example

- graphene/contrib/django/debug/sql/tracking.py
- graphene/contrib/django/debug/tests/test_query.py
- graphene/contrib/django/fields.py
- graphene/core/classtypes/objecttype.py
This pull request set the default value in a `DjangoConnection` or `DjangoFilterConnection` to be a manager, so the resolve can actually return `None` or `[]` without any trouble.
> Fix Connections and Filters for use a manager as default value

- graphene/relay/types.py
- The Relay.QL check and connection's params need
- [graphql_relay/connection/arrayconnection.py](https://github.com/graphql-python/graphql-relay-py/blob/master/graphql_relay/connection/arrayconnection.py#L55-L59) have a hard params input
- [graphql_relay/connection/connectiontypes.py](https://github.com/graphql-python/graphql-relay-py/blob/master/graphql_relay/connection/connectiontypes.py) have a default init
> change page_info to fit relay's limitation

- graphene/contrib/sqlalchemy/fields.py
Custom resolve()'s empty list return value should take precedence over SQLAlchemyConnectionField default query.
I have the following:
class Client(relay.Node):
menuitems = SQLAlchemyConnectionField(MenuItem, connection_type=ProductsOnClient)
def resolve_menuitems(self, args, info):
return self.menu_items
Without this patch, if ``self.menu_items`` is an empty list, it will be ignored and I get items from other clients.
> Allow empty list in SQLAlchemyConnectionField.

- docs/pages/docs/introspection-schema.md
> Fix wrong path to graphene.contrib.django

- graphene/contrib/django/converter.py
- graphene/contrib/django/tests/models.py
- graphene/contrib/django/tests/test_converter.py
- graphene/core/classtypes/enum.py
- graphene/core/classtypes/tests/test_enum.py
- graphene/utils/__init__.py
- graphene/utils/str_converters.py
- graphene/utils/tests/test_str_converter.py
Based on issue #134, this pull request fixes the following:
* Proper choices option handling from Django fields (fixed order)
* `to_const` method utility for converting strings into valid Pythonic constant names.
* Enum as MountedType, so could be used as:
```python
class MyObjectType(ObjectType):
enum_field = MyCustomEnum(description='This field uses Enum')
```
> Enum Improvements

- examples/flask_sqlalchemy/app.py
- examples/flask_sqlalchemy/database.py
- examples/flask_sqlalchemy/models.py
- examples/flask_sqlalchemy/schema.py
- graphene/contrib/sqlalchemy/options.py
- graphene/contrib/sqlalchemy/tests/models.py
- graphene/contrib/sqlalchemy/tests/test_query.py
- graphene/contrib/sqlalchemy/types.py
Add ability to specify custom primary key column in `SQLAlchemyNode` through an `identifier` attribute in the meta class of it
> Add meta attribute identifier for SQLAlchemyNode

- graphene/core/types/custom_scalars.py
- graphene/core/types/tests/test_custom_scalars.py
- setup.py
The DateTime scalar accepts only a small portion of valid ISO8601 date time strings.  This pull request uses the iso8601 library to improve that.
As an example here's a Date created in node.js and rendered as an ISO8601 string:
```js
> var d = new Date()
Fri Apr 29 2016 13:34:12 GMT-0500 (CDT)
> d.toISOString()
'2016-04-29T18:34:12.502Z'
```
This fails with the old parsing method:
```python 
import datetime
iso_from_node = '2016-04-29T18:34:12.502Z'
datetime.datetime.strptime(iso_from_node, "%Y-%m-%dT%H:%M:%S.%f")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_strptime.py", line 328, in _strptime
data_string[found.end():])
ValueError: unconverted data remains: Z
import iso8601 …
```
> improve iso8601 handling

- graphene/relay/tests/test_mutations.py
- graphene/relay/types.py
> Support with_context on ClientIDMutation.mutate_and_get_payload.

- docs/pages/docs/django/tutorial.md
I've found and fixed some issues in Django tutorial available at http://graphene-python.org/docs/django/tutorial/. I guess some comments were referring to an older code example.
> Fix invalid references to User model in Django tutorial

- graphene/utils/str_converters.py
- graphene/utils/tests/test_str_converter.py
Enums aren't effected if a int is passed along with the string.
> Allow numbers in to_constant

- graphene/core/tests/test_schema.py
- graphene/core/types/base.py
I ran into an issue with schemas when `auto_camelcase` was set to `False` and no middlewares were set on the resolver. This resulted in an unnamed field which could not be executed.
> Fixed bug when no middlewares are present

- graphene/contrib/django/tests/test_converter.py
It is a standard pattern in Django to enable translation of display values using the [`ugettext_lazy` function](https://docs.djangoproject.com/en/1.9/ref/utils/#module-django.utils.translation) (and related functions).
Graphene should support this usage in model field `choices`.
> Add test for django choices with translation

- graphene/contrib/django/tests/models.py
- graphene/utils/str_converters.py
When you have a translation string in a choice iterable, like this:
```py
CHOICES = (
(1, _('string to be translated')),
)
class Foo(models.Model):
bar = models.CharField(max_length=100, choices=CHOICES)
```
Graphene will fail because it passes the ugettextlazy object to ```re.sub()```. 
```
File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/types.py", line 32, in construct_fields
converted_field = convert_django_field_with_choices(field)
File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/converter.py", line 25, in convert_django_field_with_choices
return Enum(name.upper(), list(convert_choices(choices)), description=field.help_text)
File "/usr/local/lib/python2.7/dist-packages/graphene/contrib/django/converter.py", line 17, in convert_choices
yield …
```
> Fix ugettext_lazy objects in Choice tuples not being evaluated.

- graphene/contrib/django/tests/test_converter.py
It is a standard pattern in Django to group display values in [field `choices`](https://docs.djangoproject.com/en/1.9/ref/models/fields/#choices).
Graphene should support this.
> Add test for django grouped choices

- graphene/contrib/sqlalchemy/types.py
I have existing db and create User model for that db using automap_base
```python
import os
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, Column, Integer, String, ForeignKey
Base = automap_base()
class User(Base):
__tablename__ = 'users'
id = Column(Integer, primary_key=True)
email = Column('mail', String(100))
password = Column('pass', String(32))
engine = create_engine(os.getenv('DATABASE_URI'))
Base.prepare(engine, reflect=True)
```
but if I use query for users
```
query {
users {
edges {
node {
about
email
password
}
}
}
}
```
fields `email` and `password` doesn't exists because these fields are redefined in the model
> fixed model column name [sqlalchemy]

- docs/pages/docs/django/authorization.md
There is no `CategoryNode` in the authorization docs page and I believe it's actually `PostNode`,
so I fixed 2 words in the docs: `CategoryNode` -> `PostNode`
> Fix typo: CategoryNode -> PostNode

- docs/pages/docs/relay.md
For me it was not obvious that you need a node Field in your Query. I hope this makes the documentation a bit better. Also it now gives the error message that occurs if you forget the node Field, so googling for this brings you right to the documentation.
It took me way longer than I'd like to admit to find this ^^
> [Docs] Make it more obvious that the `node` Field is required for relay

- examples/flask_sqlalchemy/app.py
- examples/flask_sqlalchemy/database.py
- examples/flask_sqlalchemy/models.py
- graphene/contrib/sqlalchemy/converter.py
- graphene/contrib/sqlalchemy/tests/test_converter.py
Issue #172
Added converters for postgresql types : 
* `ARRAY`
* `JSON`
* `JSONB`
* `UUID`
* `ENUM`
* `HSTORE`
> Add postgresql dialects for sqlachemy

- graphene/core/schema.py
- graphene/core/tests/test_schema.py
- setup.py
This PR adds an additional flag to the `execute` method of the schema so that the execution returns a promise.
> Added returns_promise flag to schema.execute

- examples/starwars_relay/tests/test_connections.py
- graphene/contrib/django/types.py
- graphene/contrib/sqlalchemy/types.py
- graphene/relay/__init__.py
- graphene/relay/connection.py
- graphene/relay/fields.py
- graphene/relay/tests/test_query.py
- graphene/relay/types.py
In the Relay spec it says that the `node` of a `ConnectionField` does not actually have to be a node but can also be an objectType: https://facebook.github.io/relay/graphql/connections.htm#sec-Node
> Allow ConnectionFields to have ObjectTypes as per relay spec

- graphene/contrib/django/filter/fields.py
- graphene/contrib/django/filter/tests/test_fields.py
I came across then when trying to use `orderBy` on the `DjangoFilterConnectionField` and found I had to use the snake case version of the field name for it to actually filter values when I would have expected to be able to use the camel case version. This PR allows you to use camel case for the field name in `orderBy`.
Not sure if this breaks any current assumptions but the tests seem to pass!
> Convert `orderBy` value to snake case

- graphene/relay/tests/test_mutation.py
- graphene/relay/tests/test_node.py
- graphene/types/tests/test_objecttype.py
This is a feature that would really help us clean up our code without affecting the schema. In my opinion putting the `interfaces` on  the meta class is a great step into the right direction already and should simplify this step.
I will also add a test for subclassing/sharing fields between mutation inputs types and normal types (#66). Will also have a bit of a dig into the code-base and see if I can implement that myself.
> Added breaking test to demonstrate wanted subclassing feature.

- graphene-sqlalchemy/graphene_sqlalchemy/fields.py
pagination in graphene-sqlalchemy is currently broken as the pageInfo class is not a graphene object type. This change passes the correct PageInfo class into the `connection_from_list_slice` call
> sqla: pass pageinfo_type into connection_from_list_slice

- graphene/types/argument.py
Ensure that the assertion message correctly shows the value used by
the assertion test.
> Make assertion message use same var as test

- graphene/types/objecttype.py
- graphene/types/tests/test_objecttype.py
This succeeds https://github.com/graphql-python/graphene/pull/235 against the new `1.0` version.
> Allow initialising ObjectType with private state.

- graphene/relay/connection.py
https://facebook.github.io/relay/graphql/connections.htm#sec-Node
> relay Connection.node does not have to subclass Node/ObjectType

- graphene/types/argument.py
- graphene/types/tests/test_dynamic.py
- graphene/types/tests/test_mutation.py
- graphene/types/tests/test_query.py
- graphene/types/typemap.py
Ran into some issues when using the new `Dynamic` field. Right now it seems you have to create it as `hello_field = Dynamic(lambda: Field(String, resolver=lambda *_: 'Field World'))`, which imo is not obvious from anywhere. This changes allows to leave out the `Field` and also adds some tests, since I did not see any.
> Added tests for dynamic field and make more consistent.

- examples/starwars_relay/tests/test_objectidentification.py
- graphene/relay/connection.py
- graphene/relay/tests/test_connection.py
Ass defined in the reference implementation on https://github.com/graphql/graphql-relay-js/blob/5927f0becf43740a1f1026c6e960811c4359d342/src/connection/connectiontypes.js
Solves issue #341
> Connection Edges should be NonNull

- docs/quickstart.rst
I am contributing to the Graphene docs for the first time.  
This commit simply adds a reference to the official GraphQL docs - I haven't been able to build it locally due to graphql-python/graphene-python.org#8  but as it is a simple change, it should be ok.
> Add link to official GraphQL docs in Getting Started 

- tox.ini
Tox fails without pytz, iso8601 and pytest-benchmark
> Add tox dependencies

- graphene/relay/node.py
- graphene/relay/tests/test_global_id.py
This is pulling out some bits of #282 to make it a focused PR just trying to fix one thing. See discussion in in #282. We are most of the time overriding `GlobalID` and so it just makes it far less clean having to write `GlobalID(node=Node, required=True)` all the time, also somewhat surprising, as it was an undocumented breaking change between `0.x` and `1.x`.
Let me know if there are still any issues with that :)
> Make node arg options and default required to True for GlobalID.

- graphene/pyutils/enum.py
- graphene/pyutils/tests/test_enum.py
The conditional to test for length occured at the end of a list of conditionals causing an index error when looking at characters in the string. This reordering and test prevent that.
> Add test for _is_sunder and _is_dunder array.py functions.

- graphene/types/argument.py
- graphene/types/dynamic.py
- graphene/types/field.py
- graphene/types/inputfield.py
- graphene/types/mountedtype.py
- graphene/types/unmountedtype.py
- graphene/types/utils.py
This PR refactors the `UnmountedType`s mounting logic adding a `MountedType` that simplifies the implementation and permits more extensibility.
> Refactored mounted types logic

- docs/quickstart.rst
- docs/types/abstracttypes.rst
- docs/types/enums.rst
- docs/types/interfaces.rst
- docs/types/objecttypes.rst
- docs/types/scalars.rst
- docs/types/schema.rst
I tried my best to fix some aesthetic issues with the documentation that I stumbled upon. As English is not my first language either I tried to be very conservative, although I feel like the wording of the "Getting Started" guide could still be further improved.
> Fixed typos and improved language and markup

- graphene/types/field.py
- graphene/types/tests/test_field.py
Static methods are currently working, but it can be useful to allow class methods to work also, particularly in the context of django-graphene and using DjangoObjectType where you may have properties or methods on fatter models.
> Allow class methods to be used as a field source

- graphene/types/jsontype.py
- graphene/types/tests/test_jsontype.py
> Implement JSON type

- docs/types/mutations.rst
Not sure what the contribution requirements are for documentation. I noticed that this page: <http://docs.graphene-python.org/en/latest/types/mutations/> was a bit off.
Feel free to close PR and fix it in the "proper" way if applicable. I think this is sufficient as the README in the "graphene-python.org-docs.zip" said it was auto-generated everytime.
> Fixed indent in mutation docs

- docs/index.rst
- docs/testing/index.rst
- examples/starwars/tests/snapshots/snap_test_query.py
- examples/starwars/tests/test_query.py
- examples/starwars_relay/tests/snapshots/snap_test_connections.py
- examples/starwars_relay/tests/snapshots/snap_test_mutation.py
- examples/starwars_relay/tests/snapshots/snap_test_objectidentification.py
- examples/starwars_relay/tests/test_connections.py
- examples/starwars_relay/tests/test_mutation.py
- examples/starwars_relay/tests/test_objectidentification.py
- graphene/test/__init__.py
- setup.py
This PR adds a dummy test graphql `Client` that helps to test.
```python
from graphene.test import Client
def test_hey():
client = Client(my_schema)
executed = client.execute('''{ hey }''')
assert executed == {
'data': {
'hey': 'hello!'
}
}
```
Also, uses [SnapshotTest](https://github.com/syrusakbary/snapshottest) for **testing the examples with less code**!
First time executing the tests will create *automatically* the [snapshots directory](https://github.com/graphql-python/graphene/tree/features/test-client-and-snapshot-testing/examples/starwars/tests/snapshots) with the contents of the api client response.
Then, next time all snapshots will be compared with the previous value, raising an error if there is any mismatch.
This helps **incredibly** the amount of time required to write …
> First version of the Graphene test client and snapshots 💪

- docs/types/enums.rst
- graphene/types/enum.py
- graphene/types/tests/test_enum.py
This PR adds the ability to compare `graphene.Enum` members with their values:
```python
class RGB(Enum):
RED = 1
GREEN = 2
BLUE = 3
assert RGB.RED == 1
assert RGB.GREEN == 2
assert RGB.BLUE == 3
```
Also, adds a similar syntax to the native Python `Enum` getters:
```python
class RGB(Enum):
RED = 1
GREEN = 2
BLUE = 3
assert RGB.get(1) == RGB.RED
assert RGB['RED'] == RGB.RED
```
@dewiniaid
> Improved enums comparison and getters

- docs/relay/nodes.rst
The link to the official Facebook Relay doc is missing. This updates the link of to the appropriate link
> Update Relay Documentation Link

- docs/execution/execute.rst
`he` -> `the`.
Those tabs removal might not be necessary. Request to undo as you want.
> fix typo in docs/execution

- MANIFEST.in
Hey-lo,
I'm [building a version](https://github.com/conda-forge/staged-recipes/pull/3013) of `graphene` using [`conda`](http://conda.pydata.org/) for [conda-forge](http://conda-forge.github.io/). When possible, we try to include a link to the license file in the `meta.yaml` specification for the build; doing so requires the license be indexed in an explicit [`MANIFEST.in`](https://docs.python.org/2/distutils/sourcedist.html#manifest-related-options) file so that it gets included in the source distribution.
This pull should update the manifest so that the license is included in future builds.
> Include license in manifest for source bundles

- docs/types/objecttypes.rst
> Fix doc typo

- docs/types/enums.rst
> Fixed minor grammatical error

- setup.py
I have a project still in 1.2.0 that has been broken in my last release since it used `'graphql-core>=1.0.1'` in the `install_requires`. Since `graphql-core` has released version 2.0 with breaking changes and there was no instruction to maintain version 1, it was included as a dependency. This prevents this situation for the future.
> Prevent requirement breaking changes

- docs/relay/mutations.rst
With the current documentation, I get after execution:
"graphql.error.located_error.GraphQLLocatedError: name 'context' is not defined"
I don't get any error after the correction I made (I haven't yet tried to upload a file…)
> fix documentation to access to the request in Django

- graphene/types/enum.py
- graphene/types/tests/test_enum.py
- graphene/types/typemap.py
This Pr enhances graphene Enum support in a couple of ways:
1. if `description` for the enum wasn't explicitly defined we use the its `__doc__` value
2. allow `graphene.Enum.from_enum` to get `description` and `deprecation_reason` lambdas to allow us to define a GraphQL output for a python enum without needing to change the actual enum and add a description property there:
```
def custom_description(value):
if not value:
return "StarWars Episodes"
return 'New Hope Episode' if value == Episode.NEWHOPE else 'Other'
PyEpisode = PyEnum('PyEpisode', 'NEWHOPE,EMPIRE,JEDI')
Episode = Enum.from_enum(PyEpisode, description=custom_description)
```
> Support from_enum description lambda

- docs/types/unions.rst
fix unions.rst docs (copy-paste sentence from interfaces.rst):
`This example model defines a Character interface with a name. Human and Droid are two implementations of that interface.`
Sentence is copy-pasted from interfaces.rst and contains false information.
> fix unions.rst

- graphene/types/inputobjecttype.py
- graphene/types/tests/test_typemap.py
Previously, this only set fields that were explicitly provided in the query.  Optional input fields that were _not_ provided in the query were left as Graphene field definition types (such as `List` or `ID`).
> Set all fields on input object types

- docs/execution/middleware.rst
"Hash" in the Python world implies a cryptographic hash, or possibly a checksum. Here, I believe "hash" is being used to mean "hash map", which would be more commonly known in Python as a dictionary, or dict for short.
> Use more Pythonic terminology here

- docs/relay/nodes.rst
Specifically, get_node_from_global_id.
> Relay documentation reflects api changes in 2.0

- graphene/types/tests/test_typemap.py
- graphene/types/typemap.py
Current it errors with `AttributeError: 'NoneType' object has no attribute 'graphene_type'` if the type is not in the typemap. This PR improves that error.
> Raise better error if type is missing from schema

- docs/execution/middleware.rst
In the `timing_middleware` example, introspection queries will fail due to `Schema` and others not having `_meta` attributes. API will work and tests pass but introspection will fail, which can be quite confusing to the developer. Simple update makes sure the `root` variable has a `_meta` attribute before accessing it.
> Update middleware example to support introspection

- docs/types/list-and-nonnull.rst
List items being nullable is something that I came across recently and it wasn't immediately obvious how to mark them as not nullable, so I decided to document the solution.
> Add documentation on NonNull lists

- .gitignore
Pytest 3.4.0 changes the default cache directory from `.cache` to `.pytest_cache`.
Changelog: https://docs.pytest.org/en/latest/changelog.html#pytest-3-4-0-2018-01-30
> Update .gitignore for pytest 3.4+

- UPGRADE-v2.0.md
- graphene/relay/connection.py
- graphene/types/abstracttype.py
- graphene/types/mutation.py
Various bits of the code links to GitHub files at `2.0`, which is broken (404 Not Found).
This updates the broken links to `v2.0.0`, which works. (I'm guessing that's the intended target.)
> Fix broken GitHub link tags: 2.0 -> v2.0.0

- graphene/relay/connection.py
- graphene/relay/tests/test_connection.py
Came across this when setting up Relay Connections in my schema. Worked around it by subclassing ConnectionField but thought I'd contribute the fix upstream.
> Fix bug when setting a Relay ConnectionField to be required

- graphene/types/datetime.py
- graphene/types/tests/test_datetime.py
This change makes it so that when an incorrectly formatted date string gets passed to a Date / Time argument a GraphQLError is returned rather than a GraphQLLocatedError. Since Date / Time are types, their errors should not be in the same class as errors in your application. This is also inline with how other types work in graphene (graphene.Int, graphene.Float)
In our application, we hide all GraphQLLocatedErrors from the client as we don't wish to leak application information. As such this change is crucial for the users of our application to get any feedback about what they did wrong.
> Made DateTime types return GraphQLError on fail

- docs/index.rst
The Graphene-Mongo integration is missing from the intergration index. So I added the Graphene-Mongo docs to the integration index.
[Graphene-Mongo repo](https://github.com/graphql-python/graphene-mongo)
[Graphene-Mongo docs](http://graphene-mongo.readthedocs.io/en/latest/)
Thank you for your efforts.
> add Graphene-Mongo to intergrations index of docs/index.rst

- .pre-commit-config.yaml
- UPGRADE-v2.0.md
- examples/complex_example.py
- graphene/pyutils/enum.py
- graphene/pyutils/signature.py
- graphene/relay/tests/test_node_custom.py
- graphene/types/tests/test_base.py
- graphene/types/tests/test_datetime.py
- graphene/types/tests/test_json.py
- graphene/types/tests/test_uuid.py
- graphene/utils/tests/test_annotate.py
- graphene/utils/tests/test_deprecated.py
- graphene/utils/tests/test_resolve_only_args.py
- tox.ini
Add pre-commit https://pre-commit.com/ and a config with a minimal set of hooks. Run on all files with `tox -e pre-commit` (also gets run as part of `tox`). I added a couple pep8 rules to the ignore list that were causing some not-pretty formatting and I didn't want to do any manual restyles as part of this PR. That said, I'm happy to change the config or ignored rules however the maintainers prefer. 
Similar PR for graphql-core: https://github.com/graphql-python/graphql-core/pull/178
> Add pre-commit tool to repository, and run on all files

- README.md
- docs/conf.py
- tox.ini
Followup suggestion by @jkimbo over on https://github.com/graphql-python/graphene/pull/741 to:
1. Have tox pytest cmd match Travis command
2. Update README contributing info to include mention of using `tox`.
> Update contributing docs about using tox and sync tox pytest cmd with travis

- graphene/utils/deprecated.py
Warning filtering is the responsibility of the application, not a library, and this current use causes all warnings from an application (at least those after this function is evaluated the first time) to print their contents.
This makes the library a better citizen in the Python ecosystem, and more closely matches what developers would expect.
(For what it's worth, we also can't start using this library without this patch because the logging is too verbose and may obscure more important warnings. We depend on being able to accurately control warning and logging output)
> Fix warning output

- graphene/tests/issues/test_720.py
- graphene/types/inputobjecttype.py
As discussed in #720, the InputObjectType overwrites the fields on its `_meta` object even if fields were provided. This PR fixes it and provides a test that fails without the fix.
> Don't overwrite fields on InputObject - closes #720

- graphene/utils/crunch.py
- graphene/utils/tests/test_crunch.py
Similar to https://github.com/graphql-python/graphene/pull/786 this PR implements graphql-crunch in python.
Unfortunately I'm not seeing any benefit when running it on our code base (it actually increases response size by a bit) but hopefully it's useful for someone else.
> Crunch response data

- graphene/utils/deduplicator.py
- graphene/utils/tests/test_deduplicator.py
Inspired by https://github.com/graphql-python/graphene/issues/783 and https://github.com/graphql-python/graphene/issues/782 I've implemented https://github.com/gajus/graphql-deduplicator in python.
```python
result = schema.execute(query)
result.data = deflate(result)
```
> Deduplicator

- .pre-commit-config.yaml
- .travis.yml
- docs/conf.py
- tox.ini
Goal: use tox script in travis to run tests.
> Update .travis.yml file to use tox as script for running tests

- docs/execution/execute.rst
- docs/testing/index.rst
- examples/context_example.py
- examples/starwars/tests/test_query.py
- graphene/types/tests/test_datetime.py
- graphene/types/tests/test_decimal.py
- graphene/types/tests/test_generic.py
- graphene/types/tests/test_json.py
- graphene/types/tests/test_query.py
- graphene/types/tests/test_uuid.py
Changed in https://github.com/graphql-python/graphql-core/pull/185 , the docs here were out of date, as were the tests.
> Change deprecated execute() arguments to new ones

- graphene/types/typemap.py
I noticed this was missing. Not sure if there's a reason that it's missing, but this certainly seems to be supported in schemas, SDL, GraphiQL, etc.
> Expose documentation for Union types

- graphene/relay/connection.py
This adds documentation in the API for `PageInfo`s and `Edges`.
This is useful to include in Graphene because `PageInfo` is always the same, and Edges always have the same format, so documentation for both can be created automatically.
> Add basic type documentation for Relay fields

- docs/Makefile
```bash
> make
Please use `make <target>' where <target> is one of
applehelp                       to make an Apple Help Book
changes                         to make an overview of all changed/added/deprecated items
coverage                        to run coverage check of the documentation (if enabled)
devhelp                         to make HTML files and a Devhelp project
dirhtml                         to make HTML files named index.html in directories
doctest                         to run all doctests embedded in the documentation (if enabled)
dummy                           to check syntax errors of document sources
epub                            to make an epub
gettext                         to make PO message catalogs
html                            to make standalone HTML files …
```
> inline doctstring of make targets

- .pre-commit-config.yaml
Precommit wasn't working for me on Python 3.7
> Don't enforce python 3.6 on precommit

- docs/execution/dataloader.rst
I've recently encountered a bug caused by a dataloader returning the objects in a different order than the keys, so I thought it would be nice to have that explicitly said in the documentation.
> Improve dataloader doc

- docs/quickstart.rst
- setup.py
Fixes #872 
Latest version is forcing `long_description` to ASCII. This is a little invasive but tools reading PKG-INFO seem to struggle with special characters too.
> Special characters in README.rst break setup.py on Windows

- README.md
- README.rst
* change header of contributing docs to building docs
closes #504
> Add Docs link to readme

- graphene/types/resolver.py
- graphene/types/tests/test_resolver.py
I've created a `dict_or_attr_resolver` so that you can pass dicts or objects to object types.
I've also set it as the default resolver since I can't think of a downside but let me know if you don't think thats a good idea.
> Dict or attr default resolver

- docs/types/objecttypes.rst
Now that the default resolver handles both objects and dicts: https://github.com/graphql-python/graphene/pull/638
> Update object type docs

- graphene/relay/connection.py
- graphene/relay/tests/test_connection.py
When we declare the Connection `node` to be `NonNull` like below,
```python
class MyConnection(Connection):
class Meta:
node = NonNull(String)
```
we fail the assertion 
```python
assert issubclass(node, (Scalar, Enum, ObjectType, Interface, Union, NonNull))
```
However, this should be allowed according to the [Relay Connection specification](https://facebook.github.io/relay/graphql/connections.htm#sec-Node),
> An “Edge Type” must contain a field called node. This field must return either a Scalar, Enum, Object, Interface, Union, or a Non‐Null wrapper around one of those types.
Alternatively, we could define the `Edge` in the connection.
```python
class MyConnection(Connection):
class Meta:
node = String # We have another assertion that make this `Meta` field required!
class Edge:
node = …
```
> Allow the Connection node to be wrapped in a `NonNull` type

- setup.py
I accidentally updated my local aniso8601 to 6.0.0. My projects were running fine with graphene==2.1.3 and aniso8601==6.0.0. Later, I noticed the pip warnings telling me they were incompatible versions.
I ran tox against aniso8601 versions 4.0.0, 5.0.0, and 6.0.0 and compared against the results from running against 3.0.2. Results look the same at a glance.
> Update aniso8601 dependency to allow versions 4+.

- docs/types/objecttypes.rst
Adds missing word in docs.
schema will the same as the class ->  schema will be the same as the class
> Typo in documentation

- graphene/types/tests/test_datetime.py
Always use fixed values for tests to avoid flaky results in CI.
> Fix flaky date tests

- CODEOWNERS
Adds @dvndrsn @phalt @changeling as CODEOWNERS for /docs/ and /examples/ changes so they can update/review/approve documentation changes.
> updating codeowners to have additional reviewers for docs and examples

- .gitignore
- Makefile
- docs/Makefile
- docs/api/index.rst
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- graphene/types/argument.py
- graphene/types/context.py
- graphene/types/enum.py
- graphene/types/field.py
- graphene/types/inputfield.py
- graphene/types/inputobjecttype.py
- graphene/types/interface.py
- graphene/types/json.py
- graphene/types/mutation.py
- graphene/types/objecttype.py
- graphene/types/schema.py
- graphene/types/structures.py
- graphene/types/union.py
- graphene/types/unmountedtype.py
- graphene/types/uuid.py
Autobuild was previously set up in Makefile, but did not have its requirements frozen in `requirements.txt` and the command was not documented well. Added API level documentation for parameters and arguments for the core graphene objects.
- Added `make docs-live` target to the root project Makefile. This starts a live http server which refreshes with docs changes.
- Added `sphinx-autobuild ` to documentation requirements.
- Added `autodoc` configuration to generate documentation from classes automatically.
- API documentation attributes and parameters for core graphene objects and interfaces.
- General tidying and documentation.
- Fixed a flakey test involving `datetime.now()` by setting static values for times in tests.
> expose livehtml autobuild in Makefile + Add API autodoc

- UPGRADE-v1.0.md
- UPGRADE-v2.0.md
- docs/execution/dataloader.rst
- docs/execution/execute.rst
- docs/index.rst
- docs/quickstart.rst
- docs/relay/connection.rst
- docs/types/index.rst
- docs/types/interfaces.rst
- docs/types/mutations.rst
- docs/types/objecttypes.rst
- docs/types/scalars.rst
- docs/types/schema.rst
- Add missing reference to `flask-graphql` in integrations
- align documentation for resolver arguments (use root for 1st argument
instead of self)
- explore use of `parent` instead of `root` for first argument
- clarify resolvers and object type documentation
- add documentation for Meta class options for ObjectType
- expand quickstart documentation for first time users
- streamline order of documentation for first time users (broad ->
specific)
- document resolver quirks
> Revise documentation

- setup.py
This was changed on https://github.com/graphql-python/graphene/pull/935 to fix a warning when installing newer versions but we are now getting an error that 6.0.0 doesn't match 6.0.*:
```
ERROR: graphene 2.1.5 has requirement aniso8601<=6.0.*,>=3, but you'll have aniso8601 6.0.0 which is incompatible.
```
I don't think that the `*` are recognized as the same version.
> Fix malformed version on aniso8601 requirement

- .travis.yml
- setup.py
Graphql-relay was recently released with a restriction on graphql-core=<2. However graphene relies on graphql-core>=2,<3 which is causing issues: https://github.com/graphql-python/graphql-relay-py/issues/23
https://github.com/graphql-python/graphene/issues/1031
> Upgrade graphql-relay

- graphene/types/mutation.py
- graphene/types/objecttype.py
- graphene/types/tests/test_mutation.py
Allow mutations to apply the `interfaces` META argument to have the payload object type implement the desired interfaces.
Fixes #994
> Add interfaces meta argument on Mutations

- graphene/relay/node.py
- graphene/relay/tests/test_node.py
Closes #1035 
Question: Should all `**kwargs` from `NodeField`'s constructor be propagated or should there be any check to ensure the field gets no arguments other than `id`?
Edit 1: I also moved the "The ID of the object" description to the ID argument instead of the whole Field, since it seemed more appropriate, and included `description` in the propagated arguments.
> Propagate arguments of relay.NodeField to Field

- docs/execution/execute.rst
`a query a schema` should be `a query against a schema`
> Fix typo in execute.rst

- setup.py
A newer version 8.0.0 of aniso8601 has been released.
The only change doesn't seem to break graphene.
https://bitbucket.org/nielsenb/aniso8601/pull-requests/12/allow-commas-as-decimal-separators-on-time/diff
> Increase the allowed version of aniso8601

- docs/types/objecttypes.rst
* Create namedtuple as expected
* Access result.data instead of result['data']
* Refer to field with camel-case name
> Fix objecttypes DefaultResolver example (#1087)

- graphene/utils/str_converters.py
- graphene/utils/tests/test_str_converters.py
- setup.py
> Use unidecode to handle unicode characters in constant names

- examples/starwars_relay/tests/snapshots/snap_test_objectidentification.py
- graphene/relay/tests/test_mutation.py
- graphene/types/inputfield.py
- graphene/types/tests/test_query.py
- setup.py
- tests_asyncio/test_relay_mutation.py
Since GraphQL 3.0 there is a distinction between None and INVALID (no value).
The tests captured the bug and are updated.
See also https://github.com/graphql-python/graphql-core-next/pull/66#issuecomment-557688621
I think there are more bugs of this kind, but since I don't know graphene well, yet, I take baby steps.
I could not track the snapshot differences, the order is wrong and master has the same problem too. If master is solved I'll rebase this PR. @jkimbo has the same differences in his commits.
> The default_value of InputField should be INVALID

- graphene/relay/node.py
- graphene/relay/tests/test_node.py
It was really difficult to determine that I wasn't using the correct format for an ID.
It was previously returning null, it now returns an error.message with `Incorrect Padding` and displays the exception traceback inside the server logs.
I'm not sure about whether `return None` is/was intended functionality.
I do see some of the tests are failing:
```
_________________________ test_node_query_incorrect_id _________________________
def test_node_query_incorrect_id():
executed = schema.execute(
'{ node(id:"%s") { ... on MyNode { name } } }' % "something:2"
)
>       assert not executed.errors
E       assert not [GraphQLError("Unable call from_global_id, is the id base64 encoding of 'TypeName:id': something:2 Exception: Incorrect padding", 
locations=[SourceLocation(line=1, column=3)], …
```
> Add a helpful message to when a global_id fails to parse.

- graphene/types/interface.py
Fixed typo in class `Interface`
> fix typo in class 'Interface'

- docs/quickstart.rst
From the "Querying" section of the quickstart doc:
```
query_string = '{ hello }'
result = schema.execute(query_string)
print(result.data['hello'])
query_with_argument = '{ hello(name: "GraphQL") }'
result = schema.execute(query_with_argument)
print(result.data['hello'])
```
(https://docs.graphene-python.org/en/latest/quickstart/#querying)
"Hello stranger" should also end with a `!`
> Fix example query in quickstart doc

- graphene/types/datetime.py
This PR fixes #1142 by importing `INVALID` from `graphql` instead of `graphql.errors` in `graphene/types/datetime.py`.
> Fixed import causing Graphene v3 to crash

- graphene/types/schema.py
Following on from https://github.com/graphql-python/graphene/pull/1143 replace `INVALID` with `Undefined`
> Replace INVALID with Undefined

- docs/execution/execute.rst
- graphene/types/schema.py
- tests_asyncio/test_subscribe.py
This is my first ever pull request so please be kind :)
This adds subscription functionality to v3 by introducing a `subscribe` method to the schema.
```python
import asyncio
from datetime import datetime
from graphene import ObjectType, String, Schema, Field
class Query(ObjectType):
hello = String()
def resolve_hello(root, info):
return 'Hello, world!'
class Subscription(ObjectType):
time_of_day = Field(String)
async def subscribe_time_of_day(root, info):
while True:
yield { 'time_of_day': datetime.now().isoformat()}
await asyncio.sleep(1)
SCHEMA = Schema(query=Query, subscription=Subscription)
async def main(schema):
subscription = 'subscription { timeOfDay }'
result = await schema.subscribe(subscription)
async for item in result:
print(item.data['timeOfDay'])
asyncio.run(main(SCHEMA)) …
```
> Added support for subscription

- .pre-commit-config.yaml
- UPGRADE-v2.0.md
- docs/execution/middleware.rst
- docs/relay/nodes.rst
- docs/types/objecttypes.rst
- examples/complex_example.py
- graphene/relay/connection.py
- graphene/relay/mutation.py
- graphene/relay/node.py
- graphene/relay/tests/test_connection_query.py
- graphene/types/argument.py
- graphene/types/base.py
- graphene/types/datetime.py
- graphene/types/decimal.py
- graphene/types/field.py
- graphene/types/mountedtype.py
- graphene/types/mutation.py
- graphene/types/objecttype.py
- graphene/types/schema.py
- graphene/types/structures.py
- graphene/types/tests/test_datetime.py
- graphene/types/tests/test_enum.py
- graphene/types/tests/test_inputobjecttype.py
- graphene/types/tests/test_query.py
- graphene/types/tests/test_type_map.py
- graphene/types/union.py
- graphene/types/unmountedtype.py
- graphene/types/uuid.py
- graphene/utils/deprecated.py
- graphene/utils/subclass_with_meta.py
> Updated all str.format(…) to f-strings

- graphene/types/schema.py
Looks like this function is a duplicate of `get_resolver_for_type` so removing it so that it doesn't cause any confusion.
> Remove unused function

- graphene/types/field.py
- graphene/types/tests/test_field.py
This PR fixes a bug where if you were using the `source` attribute on a field (https://docs.graphene-python.org/en/stable/api/#fields-mounted-types) it wouldn't work if the root value was a dictionary. The fix is to change the code to use use the `default_resolver` method which accepts both objects and dictionaries.
> Use default_resolver to resolve values when using the source attribute

- docs/types/objecttypes.rst
The current documentation shows all of the resolve parameters on a single line as opposed to the bullet list that was intended.
> Fix resolve method parameters bullet list

- README.md
- README.rst
It's nice to just be able to copy/paste the entire example without
having to remember the import (aka I'm lazy).
> added graphene import to READMEs

- setup.py
As #1110 correctly states, currently `examples` package is installed alongside `graphene` which is probably not intended as `"examples"` is listed in `packages=find_packages(exclude=[...])` list.
I was able to fix it by changing examples in:
`packages=find_packages(exclude=["tests", "tests.*", "examples"])`
to examples*:
`packages=find_packages(exclude=["tests", "tests.*", "examples*"])`
Unfortunately there seems to be no easy way to make package examples an optional dependency when it is in the same repository. Maybe it will be a good idea to separate examples from main package and then it could be added as extras_require={"examples": ["graphene-examples"]}?
Is it even necessary to allow installation of examples or are they here only for documentation purposes?
_Additional question:_
I …
> Update excluded packages list to properly exclude examples package

- docs/types/mutations.rst
Fixes #1205
The staticmethod decorator is causing confusion and it should at least be consistent in the documentation.
> Remove @staticmethod decorator in mutations doc

- graphene/utils/str_converters.py
- graphene/utils/tests/test_str_converters.py
- setup.py
Fixes https://github.com/graphql-python/graphene/issues/1208
Related PR in Graphene-Django: https://github.com/graphql-python/graphene-django/pull/992
> Remove to_const function

- docs/types/mutations.rst
- graphene/types/schema.py
> Update requirement for Query type in mutation docs

- docs/relay/nodes.rst
- graphene/pyutils/dataclasses.py
- graphene/relay/connection.py
- graphene/relay/node.py
- graphene/relay/tests/test_node_custom.py
- graphene/types/argument.py
- graphene/types/dynamic.py
- graphene/types/field.py
- graphene/types/inputfield.py
- graphene/types/tests/test_definition.py
Co-authored-by: Daniel Gallagher <daniellg@yelp.com>
This is the continuation of #738 . I rebased it on master and replaced `type` with `type_` in some places not covered by the original PR (due to its age).
This PR is related to #1127 and finally fixes #700.
> Rename variables called type to type_

- docs/types/mutations.rst
- graphene/types/schema.py
- graphene/types/tests/test_schema.py
Unfortunately it looks like graphql-core v3 requires a Query root type: https://github.com/graphql-python/graphql-core/blob/ffdf1b3702505cbcfd9fca7d6bde191e7d3f5e47/src/graphql/type/validate.py#L114 (v2 didn't have that check)
This PR reverts graphql-python/graphene#1213 because with the release of Graphene v3 this will no longer be the case. I've also added a test to check the expected behaviour.
FYI @sydoluciani
> Revert 1213 update mutation docs

- docs/execution/execute.rst
- docs/execution/index.rst
- docs/execution/subscriptions.rst
There was a bug in the example code for subscriptions. This PR fixes it as well as moving the documentation into a seperate file.
> Split out the subscriptions documentation a separate file and fix it

- docs/execution/execute.rst
The example of executing a query by passing a root value had a typo for
the trailing parenthesis, namely it was '}' instead of ')'.
> Fix Typo in Docs

- graphene/types/scalars.py
- graphene/types/tests/test_scalar.py
Custom type for bigger integers.
While less compatible (according to the GraphQL spec) it works for most major JS implementations.
> add BigInt type

- graphene/types/schema.py
- graphene/types/tests/test_schema.py
Resolves: https://github.com/graphql-python/graphene/issues/902
I'm not sure what the best place to add this execution context is. I'm happy to change naming and where this is defined to whatever is most appropriate.
Assuming this approach looks good, this probably also warrants some updates to the docs before merging.
Note that I have not added this as the default execution context since that would be a pretty breaking change. If a breaking change is ok, I'll update this PR.
In the project where I've taken a similar approach, I also added an `assert graphl.version == '3.1.1'` as a reminder to check the underlying implementation for changes when bumping versions. It might be worth adding a similar check here as well
> Add UnforgivingExecutionContext

- docs/relay/index.rst
The official Relay project has removed 'Relay input Object Mutation' in favour of general mutation spec from their docs in [this PR](https://github.com/facebook/relay/pull/2401/files#diff-98bee0595817d7a46cd52d86e6c3db70) and is unavailable on their [official website](https://relay.dev/docs/en/graphql-server-specification#further-reading) as well
> Remove Object Mutation dead link from Relay docs

- graphene/types/decimal.py
- graphene/types/tests/test_decimal.py
- tox.ini
* Accept IntNode into decimal type
* Add test exhibiting failure
* Enable py38 in tox
> fix(Decimal): parse integers as decimal. 

- graphene/types/schema.py
- graphene/types/tests/test_type_map.py
The [GraphQL spec](https://github.com/graphql/graphql-spec/pull/418) allows a required argument to have a default value. In fact, [Graphene v2 supports this behavior](https://github.com/graphql-python/graphene/blob/v2/graphene/types/typemap.py#L294). However, for some reason, this is not allows in [Graphene v3](https://github.com/graphql-python/graphene/pull/1048/files#diff-f066ce1b84329fbfb7cd0e5d5027a51f68e14677754aab172fbc91dea42c519dR360-R362).
> Use argument's `default_value` regardless if the input field is required

- graphene/relay/node.py
- graphene/relay/tests/test_node.py
* Propagate name, deprecation_reason arguments of relay.NodeField to Field
* Allow custom description in Node.Field and move ID description to ID argument
* Add test for Node.Field with custom name
* Add tests for description, deprecation_reason arguments of NodeField
* Pass all kwargs from NodeField to Field
> Propagate arguments of relay.NodeField to Field (#1036)

- docs/execution/execute.rst
fix field name in execute.rst 'Operation Name' example
> fix field name in execute.rst example

- setup.py
The latest `aniso8601` release 9.0.1. With 9.x.x was the support for Python 2 [removed](https://bitbucket.org/nielsenb/aniso8601/src/master/CHANGELOG.rst).
Distributions are starting to ship `aniso8601-9.0.1` which is not covered by the current version constraint.
> Allow later aniso8601 releases

- setup.py
The pinning to a "very" old release makes it hard to build distribution packages without patching.
> Update pytz to 2021.1

- setup.py
GraphQL-core released `3.2.0rc1` with some breaking changes and
1. We should be getting RC releases in our dependencies
2. It has breaking changes, so we shouldn't get 3.2.0 unless someone fixes it explicitly
> Fix GraphQL-core dependency

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- .pre-commit-config.yaml
- graphene/types/tests/test_objecttype.py
- setup.py
- tox.ini
Also update the test dependencies and adapt two tests (#1400).
> Add Python 3.9 and 3.10 to the test matrix

- UPGRADE-v2.0.md
maybe `(first, before, after, before)` is `(first, last, after, before)`?
> fix UPGRADE-v2.0.md

- graphene/tests/issues/test_1419.py
- graphene/types/base64.py
- graphene/types/decimal.py
- graphene/types/generic.py
- graphene/types/json.py
- graphene/types/scalars.py
- graphene/types/uuid.py
This is to match the `graphql-core` API. If it's not respected
the `parse_literal` method will produce an error event though
dealing with a valid value.
> fix: add default param _variables to parse_literal #1419

- UPGRADE-v1.0.md
- UPGRADE-v2.0.md
- docs/execution/fileuploading.rst
There are small typos in:
- UPGRADE-v1.0.md
- UPGRADE-v2.0.md
- docs/execution/fileuploading.rst
Fixes:
- Should read `standard` rather than `stantard`.
- Should read `library` rather than `libary`.
- Should read `explicitly` rather than `explicity`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- docs/types/enums.rst
When I first read through the documentation twice, it took me two tries and looking very hard to find out the difference b/w the two. The background highlight using backticks would be helpful in this case.
> Highlight .get in backticks

- graphene/types/interface.py
- graphene/types/schema.py
- graphene/types/tests/test_interface.py
- graphene/types/tests/test_type_map.py
`graphql-core` [already supports specifying interfaces on interfaces](https://github.com/graphql-python/graphql-core/blob/7d826f0ec0a447cb869dfb891a755dbe8ea9b66f/src/graphql/type/definition.py#L819). This change adds that support to graphene.
For example, the interfaces from one of the added test cases would look like this in a printed schema:
```graphql
interface FooInterface {
foo: String
}
interface BarInterface implements FooInterface {
foo: String
bar: String
}
```
I've tested these changes with a private schema and it seems to work as expected. There's some trickiness around getting graphql-core to resolve types properly but it's definitely doable.
> Add support for interfaces on interfaces

- graphene/types/mutation.py
The code example in docstring starts with `from graphene import Mutation` and defines a `class Mutation` later. This definition would shadow previously imported name and (which is more important) confuses a reader about usage of this class — one need to keep in mind that previous usage of `Mutation` is imported from graphene and have not been overridden yet.
This PR changes an "import-from" statement to an "import" statement, so `graphene.Mutation` is referred explicitly. This approach seems to be consistent with other code examples in the docs (e. g. see https://docs.graphene-python.org/en/v2.1.9/types/mutations/).
Another option is to change name of example class Mutation to something more explicit (maybe SchemaMutation or RootMutation), but I'm not sure what name to choose.
Only …
> Avoid ambiguity in graphene.Mutation docstring [documentation]

- docs/types/scalars.rst
- graphene/tests/issues/test_1419.py
- graphene/types/decimal.py
- graphene/types/json.py
- graphene/types/scalars.py
- graphene/types/tests/test_decimal.py
- graphene/types/tests/test_json.py
- graphene/types/tests/test_scalar.py
- graphene/types/tests/test_scalars_serialization.py
- graphene/types/tests/test_uuid.py
- graphene/types/uuid.py
The failure in the CI exists on master as well.
You can find the fix on the PR #1412
> Issue #1413 fix invalid input type

- README.md
- README.rst
> fix: use install instead of instal for consistency

- .github/workflows/tests.yml
https://www.python.org/download/pre-releases
> Add Python 3.11 release candidate 1 to the testing

- graphene/types/schema.py
Fixed type of Schema(query) to correct one `Type[ObjectType]`
> Fix documentation typing in schema.py for v2

- graphene/types/definitions.py
- graphene/types/tests/test_definition.py
Fixes https://github.com/graphql-python/graphene/issues/1333
First found in a Django project while upgrading to graphene 3. Django's `setUpTestData` tries to create a copy of a GrapheneGraphQLType and raises a `KeyError: 'graphene_type'`. This doesn't happen in graphene 2.1.8
> Add copy function for GrapheneGraphQLType

- graphene/types/enum.py
- graphene/types/tests/test_enum.py
It would be convenient for `graphene.Enum` to be hashable the same way `enum.Enum` is so that it can be used as a key in a dict or a member of a set.
> hashable Enum

- docs/execution/middleware.rst
This PR adds a note to the middleware documentation noting the last-to-first execution order for middlewares, since #1385 indicates that some people were surprised by this behavior.
Fixes #1385
> Clarify execution order in middleware docs

- docs/quickstart.rst
As shown in #1230, the documentation has caused some confusion among new users because of `name` being simultaneously used as a keyword and as a field name. Given that most people will initially rely on the quickstart documentation, the `name` field name has been changed to something that's more obviously not a keyword.
Fixes #1230
> Disambiguate argument name in quickstart docs

- graphene/relay/tests/test_mutation_async.py
- graphene/test/__init__.py
- setup.py
Previously, installing graphene and trying to do `from graphene.test import Client` as recommended in the docs caused an `ImportError`, as the 'promise' library is imported but only listed as a requirement in the 'test' section of the setup.py file.
Based on #1297 which appears to be inactive. Fixes #1296.
> Remove unnecessary dependency on 'promise' library

- graphene/types/schema.py
- graphene/types/tests/test_enum.py
This is a workaround for `TypeError`s being raised when initialising schemas with Enum members named `description` or `deprecation_reason`.
It is still not ideal as you can't have an enum with both a "description" member and a description property. Fixing this would require some more thought though. Potentially we could allow something like `__description__` as an alternative way of naming the description property in cases where it conflicts with one of the members.
Fixes #1321 (ish)
> Do not interpret Enum members called 'description' as description properties

- graphene/types/argument.py
- graphene/types/inputfield.py
- graphene/types/schema.py
- graphene/types/tests/test_argument.py
- graphene/types/tests/test_field.py
- graphene/types/tests/test_inputfield.py
**Implementing enhancement from #1446**
In this PR I ensure that `Argument`, `Field` and `InputField` support **deprecation** functionality.
TODOs from the issue:
Skipped this one, as meta is not populated to the Mounted object.
Notes:
1. `Field` and `InputField` already had this field, whereas `Argument` didn't.
2. When constructing schema, some objects were already passing deprecation reason. I added the missing parts: `InputField` and `Argument`. `Enum` and `Field` were compliant.
3. When mounting `InputObject` or `Enum` **implicitly**, meta fields are not populated to the `Mounted` object.
> Complete deprecated fields and arguments support

- docs/types/scalars.rst
Update documentation because `graphql.language.ast.StringValue` in V2 has been renamed to `graphql.language.ast.StringValueNode` in V3.
> Correct the module name of custom scalar example in documentation

- docs/index.rst
I'm assuming v3 is no longer a prerelease and this notice should be removed 🤔  (the v2 link just takes you to the same docs so 🤷🏻‍♂️ )
> Remove prerelease notice

- README.rst
- docs/api/index.rst
- docs/conf.py
- docs/execution/queryvalidation.rst
- docs/index.rst
- docs/requirements.txt
Hello,
I first wanted to contribute to the graphene docs, but I don't manage to install it locally due to the sphinx version.
I create this MR to update the docs to the latest version of sphinx today.
Here is my changes :
- Deps : update [Sphinx](https://pypi.org/project/Sphinx/) to 6.1.3 
- Deps : update [ sphinx-autobuild](https://pypi.org/project/sphinx-autobuild/) to 2021.3.14
- Conf : remove `language = None` line to avoid warning
- Deps : update `graphql.execution.base.ExecutionResult` to `graphql.ExecutionResult` as it is imported in the code files
I still get some warnings about duplicate or missing fields, more commits will follow.
> docs: update sphinx to the latest version

- graphene/relay/connection.py
- graphene/relay/tests/test_connection.py
This PR enables users to easily modify the `relay.Connection`  type to add fields like `nodes`, or customize the existing `Edges` and  `PageInfo` fields to make changes about nullability. 
This is handy for cases like having a generic nodes field, that skips the use of edges for non-pagination use. The change is enabled by checking if `_meta` was already provided in the keyword arguments of `Node/Connection`'s `init_subclass_with_meta`, so we don't override existing field definitions from the superclass.
The most common use case will be to add a generic `nodes` field for cases where cursor-based pagination is not necessary:
```graphql
type MyTypeConnection {
pageInfo: PageInfo
edges: [MyTypeEdge]
nodes: [MyType]
}
> chore: make relay type fields extendable

- graphene/types/enum.py
- graphene/types/tests/test_enum.py
Default enum description to "An enumeration." string as opposed to trying to read `enum.__doc__` as it appears to be not set to default enum class doc in python 3.11
> Default enum description to "An enumeration."

- graphene/types/inputobjecttype.py
- graphene/types/tests/conftest.py
- graphene/types/tests/test_inputobjecttype.py
- graphene/types/tests/test_type_map.py
- graphene/validation/depth_limit.py
This PR aims to remove the ambiguity that happens with `InputObjectType`s when accessing optional fields using the `input.<attribute>` "dot access" syntax.
If an optional input field is defined but has not been specified in an incoming `InputObjectType`, it comes back as a `None`
This is ambiguous, since the user could also have set that specific field to `None`, meaning we wouldn't be able to tell between an explicit setting to `None` versus the field not being set at all.
Introduce a non-breaking, opt-in method to allow the users to change this default value getter behavior in InputObjectTypes to any value that they want to. Graphene already provides such concept in the form of the `graphl.Undefined` value, which is a good example of a value that the user could use to differentiate …
> Allow the user to change InputObjectType's default value on non-specified inputs to a sentinel value

- graphene/types/inputobjecttype.py
- graphene/types/interface.py
- graphene/types/mutation.py
- graphene/types/objecttype.py
- graphene/types/union.py
Hello graphene!
I found that the code base is using `MYPY` as a constant to tell whether a type checker is running.
According to the [mypy docs](https://mypy.readthedocs.io/en/stable/runtime_troubles.html#typing-type-checking), however, `mypy` introduces a more commonly used constant: `typing.TYPE_CHECKING`. So I'd like to suggest using this rather than `MYPY`.
As `typing.TYPE_CHECKING` has been added since Python 3.5.2 and `graphene` supports from Python 3.6, there would be no problem with backporting.
Reference:
- https://docs.python.org/ko/3/library/typing.html#typing.TYPE_CHECKING
> fix: Use `typing.TYPE_CHECKING` to provide generalized way

- graphene/relay/connection.py
- graphene/relay/tests/test_connection.py
This PR adds a `strict_types` meta option to the relay `Connection` class to simplify the use case identified in this issue: https://github.com/graphql-python/graphene-django/issues/901
Default of `False` is the old behavior, and when set to `True` generated `TConnection` types will be typed as `edges: [TEdge!]!` instead of `edges: [TEdge]!` and `TEdge` will have `node: T!` instead of `node: T`.
This avoids duplicating logic and string descriptions for subclasses which just want to implement this common behavior. If this behavior is deemed desirable by default it would be trivial to flip the flag's default or remove it entirely. It only make the types stricter so it oughtn't break any existing code (though it will cause unexpected changes to user's schema's nonetheless, which is why I …
> types: add option for strict connection types

- .isort.cfg
- graphene/types/tests/test_datetime.py
- setup.py
`pytz` is being deprecated, the usage of pytz in the package can be easily replaced by `datetime.timezone.utc`
I also plan to apply this commit to v2.
> remove pytz

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
There was deprecation warnings about GH actions, so this PR is bumping versions.
> CI: bump GH actions

- setup.py
pytest 8 is the latest version, and dropped support for Python 3.7. Also pytest-cov 5 dropped Python 3.7 too. I can update this PR to pytest 8 if https://github.com/graphql-python/graphene/pull/1543 is merged.
> bump pytest to 7

- .github/workflows/tests.yml
CI is able to restore **pip** cache as usual, and deprecation warning is gone. Please see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> CI: fix deprecation warning

- .isort.cfg
- graphene/types/datetime.py
- setup.py
Python 3.7 added **fromisoformat** functionality, so we can remove aniso8601. There are test cases for it, and all are passing..
Removing **mock**, because the documentation states below, so we don't need it.
> mock is now part of the Python standard library, available as [unittest.mock (https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
> remove aniso8601, mock, iso8601

- .github/workflows/lint.yml
- .gitignore
- .pre-commit-config.yaml
- examples/simple_example.py
- examples/starwars_relay/tests/snapshots/snap_test_objectidentification.py
- graphene/relay/tests/test_node.py
- graphene/types/enum.py
- graphene/types/tests/test_scalars_serialization.py
- graphene/utils/dataloader.py
- graphene/utils/deprecated.py
- setup.py
This PR adds format checking using Ruff tool, and formats some files for consistency. Please see https://github.com/graphql-python/graphene/actions/runs/9634079092/job/26569302721?pr=1557
I think that consistent code formats are essential for open collaboration.
Lint job error is fixed in https://github.com/graphql-python/graphene/pull/1556
> CI: format check using Ruff

- .isort.cfg
- .pre-commit-config.yaml
- bin/autolinter
- docs/conf.py
- graphene/pyutils/version.py
- graphene/relay/id_type.py
- graphene/types/__init__.py
- graphene/types/base.py
- graphene/types/scalars.py
- graphene/utils/dataloader.py
- setup.cfg
- setup.py
Ruff is modern linter that replaces flake8, isort and other linting tools, thus removing flake8. I'll add more lint check once merged.
Python 3.13 testing is fixed in https://github.com/graphql-python/graphene/pull/1562
> Lint using Ruff

- .github/workflows/build.yaml
I would like to [modernize](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/) packaging, also thought CI for building packages would be helpful for QA.
Tests on Python 3.13 are fixed in https://github.com/graphql-python/graphene/pull/1562
> CI: build package

- graphene/types/datetime.py
- graphene/types/tests/test_datetime.py
- setup.py
- tox.ini
> fix: use dateutil-parse for < 3.11 support

- graphene/types/union.py
This gives us the option to add our own `_meta` to `Union`
Allowing us to implement features such as [this](https://github.com/graphql-python/graphene-django/pull/1537)
> Override Union meta

- graphene/types/tests/test_uuid.py
- graphene/types/uuid.py
When a user sends a dictionary or other object as a UUID variable like `{[123]}`, previously graphene crashed with an `AttributeError`, like this:
```
(…)
File "…/lib/python3.12/site-packages/graphql/utils/is_valid_value.py", line 78, in is_valid_value
parse_result = type.parse_value(value)
^^^^^^^^^^^^^^^^^^^^^^^
File "…/lib/python3.12/site-packages/graphene/types/uuid.py", line 33, in parse_value
return _UUID(value)
^^^^^^^^^^^^
File "/usr/lib/python3.12/uuid.py", line 175, in __init__
hex = hex.replace('urn:', '').replace('uuid:', '')
^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'replace'
```
But an `AttributeError` makes it seem like this is the server's fault, when it's obviously the client's.
Report a proper `GraphQLError`.
> Do not raise AttributeError when parsing non-string UUIDs
