tests/core/test_types.py
And some other clean-ups because I'm slightly OCD.
=> Test resolver tags w/ tag_resolver and resolver_has_tag function.

examples/field_example.py
While getting started, I did not find a simple example of what I wanted to do here - query a Python object type and not a scalar field. Hopefully this is a good addition.
=> Example of querying a Python object

docs/pages/docs/quickstart-django.md
Feedback welcome.
I've tried to explain things for newcomers to graphql. It is possible I have some of the terminology wrong, in which case feel free to correct it where necessary. My main focus was on laying down the initial concepts.
=> Expanding on the django quickstart to make it a little more verbose

graphene/contrib/django/converter.py, graphene/contrib/django/fields.py, graphene/contrib/django/filter/__init__.py, graphene/contrib/django/filter/filterset.py, graphene/contrib/django/filter/tests/filters.py, graphene/contrib/django/filter/tests/test_fields.py, graphene/contrib/django/management/commands/graphql_schema.py, graphene/contrib/django/tests/models.py, graphene/contrib/django/tests/test_command.py, graphene/contrib/django/tests/test_schema.py, graphene/contrib/django/tests/test_types.py, graphene/contrib/django/utils.py, graphene/core/tests/test_schema.py, graphene/core/types/tests/test_argument.py, graphene/core/types/tests/test_base.py, graphene/core/types/tests/test_field.py, graphene/utils/str_converters.py, graphene/utils/tests/test_resolve_only_args.py, graphene/utils/tests/test_str_converter.py, tests/django_settings.py
Following Pull request #60, this improves the integration with optional `django-filters` support and some other improvements.
=> Improved Django integration

graphene/core/classtypes/uniontype.py
=> Fix UnionType resolver

docs/pages/docs/relay.md
I added a bit of ducumentation to describe relay mutations.
=> Add documentation for relay mutations.

docs/pages/docs/django/tutorial.md
Updated stale ingredients.json link and added a few missing steps to
make the instructions completely step-by-step.
=> Updated django quickstart tutorial

.travis.yml, docs/pages/docs/basic-types.md, examples/flask_sqlalchemy/app.py, examples/flask_sqlalchemy/database.py, examples/flask_sqlalchemy/models.py, examples/flask_sqlalchemy/schema.py, graphene/contrib/django/compat.py, graphene/contrib/django/converter.py, graphene/contrib/django/debug/tests/test_query.py, graphene/contrib/django/filter/filterset.py, graphene/contrib/django/filter/tests/filters.py, graphene/contrib/django/tests/test_converter.py, graphene/contrib/django/tests/test_query.py, graphene/contrib/sqlalchemy/converter.py, graphene/contrib/sqlalchemy/fields.py, graphene/contrib/sqlalchemy/tests/test_converter.py, graphene/contrib/sqlalchemy/tests/test_query.py, graphene/contrib/sqlalchemy/tests/test_utils.py, graphene/contrib/sqlalchemy/types.py, graphene/core/classtypes/enum.py, graphene/core/types/custom_scalars.py, graphene/utils/enum.py, setup.py
Added support for:
#137 #136 #125
=> Improved support for Django fields

setup.py
=> fix impossible dependencies of dependencies

docs/pages/docs/django/debug.md
https://github.com/graphql-python/graphene/issues/153
=> Document that __debug must be last field

graphene/contrib/django/fields.py, graphene/contrib/sqlalchemy/fields.py, graphene/relay/fields.py, graphene/relay/tests/test_query.py, graphene/relay/types.py
Added context to `ConnectionField` resolver.
Based on the work of @Globegitter #174.
=> Added context to connectionfield resolver

graphene/core/schema.py, graphene/core/tests/test_schema.py
This PR fix the issue #182 based in the PR #183 by the work of @mjtamlyn
=> Register interface failure fix

graphene/core/tests/test_schema.py
Demonstrates the issue in #182.
=> Failing test of interface implementation registration.

graphene/contrib/django/converter.py, graphene/contrib/django/tests/models.py, graphene/contrib/django/tests/test_converter.py, graphene/utils/str_converters.py
Based on the work of @JCB-K and @Ian-Foote in the pull requests: #184, #189 this PR add support for lazy translated Django text.
=> Fix lazy translated choice

graphene/contrib/django/converter.py, graphene/contrib/django/tests/models.py, graphene/contrib/django/tests/test_converter.py
This would save me from having to mark all of my fields as `NonNull` manually.
Let me know if I need to make any changes!
=> Implicitly mark Django fields as NonNull where appropriate

graphene/relay/tests/test_mutations.py, graphene/relay/types.py
=> Make clientMutationId optional

graphene/contrib/django/management/commands/graphql_schema.py
I'll create another PR for the docs (btw I'm not sure the reasoning around splitting the docs out into a separate repo but it makes things like this quite inconvenient!)
=> Added --indent option for graphql_schema command

graphene/core/types/custom_scalars.py, graphene/core/types/tests/test_custom_scalars.py
Fix for https://github.com/graphql-python/graphene/issues/223
=> Json custom scalar fix

graphene/__init__.py, graphene/relay/__init__.py, graphene/types/__init__.py
Exports union type and fixes a missing comma.
=> Export union type directly.

graphene/relay/tests/test_connection.py, graphene/relay/tests/test_mutation.py
Just started upgrading our app and these are the bits and bobs I am finding, hence all the PRs :)
=> Added test for node connection edge.

.gitignore, graphene/types/field.py, graphene/types/tests/test_field.py, graphene/types/tests/test_query.py, graphene/types/typemap.py
This is implementing `default_value` as you suggested @syrusakbary in https://github.com/graphql-python/graphene/pull/283.
=> Added default value for default resolver.

docs/types/scalars.rst
Came up because of my confusion in [Issue 329](https://github.com/graphql-python/graphene/issues/329). Hopefully this helps others!
=> Tweak the documentation to match behavior in the playground.

graphene/relay/node.py
Makes it much easier to find the issue when this error happens.
=> Improve `is_node` error message

graphene/relay/connection.py
I will add a test for this asap, this is just to get a patch for our app.
=> Add support to return a promise for connections.

docs/types/scalars.rst
These are just random bits I stumbled upon when reading the docs.
=> Various little documentation fixes

docs/types/mutations.rst
I saw there was no documentation that shows how to properly use InputFields with mutations so I thought I'd write up some.
=> Added documentation for InputFields and InputObjectTypes usage

graphene/relay/node.py, graphene/relay/tests/test_global_id.py
This is the second and I suppose more controversial part of #282. I do think it would be nice to more easily support the mutation use-case (I am also happy to add another test for this, displaying its use-case).
But let me know what you think and what reservations you have with this.
=> Node parent type

docs/types/scalars.rst, graphene/types/datetime.py, graphene/types/tests/test_datetime.py
Also changed one DateTime method to a class method so the parser doesn't have to be updated in two places if there is ever a change.
=> Added Time Type

graphene/types/tests/test_datetime.py
Had one more test for you @syrusakbary to follow the previous datetime coverage
=> add time query variable test

README.md, README.rst
Just a small typo fix on the Readme files!
Thanks for this awesome library!
=> small grammar fix on readme

docs/relay/mutations.rst, docs/types/mutations.rst
Added documentation that describes how to create a mutation that takes in files
Also fixed a few documentation bugs, there was a code type graphql instead of json, and a warning for a header underline that was too short
=> Added documentation on how to accept files in a mutation

graphene/types/enum.py, graphene/types/inputobjecttype.py, graphene/types/interface.py, graphene/types/objecttype.py, graphene/types/scalars.py, graphene/types/tests/test_objecttype.py, graphene/types/union.py, graphene/utils/tests/test_trim_docstring.py, graphene/utils/trim_docstring.py
=> Fix docstring whitespace

docs/requirements.txt
I'm new to graphene and also Sphinx. Losing one line of Sphinx installation took me 30 mins to find out.
=> Add Sphinx to requirements for building graphene docs

graphene/utils/module_loading.py, graphene/utils/tests/test_module_loading.py
Hi @syrusakbary ,
This PR is for #438. Please let me know if any improvement is needed. Hope you will like it :)
Blake
=> Improve lazy_import() to accept dotted_attributes

docs/quickstart.rst
=> Update basic schema with arguments

docs/execution/dataloader.rst
I'm thinking you meant "leaner" here? 😊
=> Fix typo in dataloader docs

docs/execution/execute.rst
added an example using `variable_values`
=> Doc was missing for using variables in queries

docs/types/enums.rst
Added docs related to PR:
https://github.com/graphql-python/graphene/pull/586
=> Improved docs for Enums

docs/execution/middleware.rst
Added an example of using a function for middleware instead of a class.
=> [Docs] Functional middleware example

docs/types/scalars.rst
Expand the scalar documentation
=> [Docs] Scalar documentation

graphene/tests/issues/test_425.py, graphene/types/enum.py, graphene/types/inputobjecttype.py
Fixes https://github.com/graphql-python/graphene/issues/566
=> extended support for subclassing with meta to Enum and InputObjectType

graphene/utils/str_converters.py, graphene/utils/tests/test_str_converters.py
=> Change .title method to .capitalize in to_camel_case() in str_convertes.py

graphene/relay/connection.py, graphene/relay/tests/test_connection.py
=> Allow ObjectType to set Connection name

setup.py
=> Exclude examples module in setup.py

graphene/types/abstracttype.py
This one updates the deprecations url in DeprecationWarning message which addressed in #690
=> Fix deprecations url

graphene/relay/node.py, graphene/relay/tests/test_node.py
Editing the assert message to name the expected value, as the message suggests the value is.
=> Resolve #750 by editing assert message

.pre-commit-config.yaml, docs/conf.py, graphene/relay/tests/test_connection_query.py, graphene/tests/issues/test_313.py, graphene/tests/issues/test_356.py, graphene/tests/issues/test_425.py, graphene/types/tests/test_abstracttype.py, graphene/types/tests/test_argument.py, graphene/types/tests/test_base.py, graphene/types/tests/test_datetime.py, graphene/types/tests/test_definition.py, graphene/types/tests/test_enum.py, graphene/types/tests/test_query.py, graphene/types/tests/test_typemap.py, graphene/utils/tests/test_annotate.py, graphene/utils/tests/test_deprecated.py, graphene/utils/tests/test_resolve_only_args.py
Add flake8 pre-commit hook and manually edit files to pass flake8 validation
=> Add flake8 pre-commit hook and manually edit files to pass flake8 validation

graphene/__init__.py
Release notes: https://github.com/graphql-python/graphene/releases/tag/untagged-1991a1163a7e751e5d0e
=> Update to v2.1.2

docs/types/index.rst, docs/types/interfaces.rst
Updated the interface documentation so that it follows the (GraphQL learn)[https://graphql.org/learn/schema/#interfaces] docs. Also added some documentation for `resolve_type`
=> Update interface documentation

docs/types/enums.rst, docs/types/interfaces.rst, docs/types/objecttypes.rst
=> Fixed typos.

docs/quickstart.rst, docs/types/objecttypes.rst, graphene/utils/str_converters.py
=> Update documentation on ObjectTypes

CODEOWNERS
Adding the code owners as decided in our community meeting so that we can start processing and approving PRs
=> Added CODEOWNERS 

docs/execution/middleware.rst
=> Fixes middleware documentation

docs/index.rst
Add [FastAPI](https://github.com/tiangolo/fastapi) and [Starlette](https://github.com/encode/starlette) to integrations in the docs.
=> Add FastAPI and Starlette to integrations

docs/types/objecttypes.rst
Fixes https://github.com/graphql-python/graphene/issues/839
=> Docs on changing the name of an ObjectType

docs/execution/execute.rst
Fixes https://github.com/graphql-python/graphene/issues/890
=> Update execution doc with correct way to use variables

docs/types/enums.rst
Line too long in code sample caused docs UI to overflow
(Issue #924 )
=> Fix enum docs overflow (Issue #924)

graphene/types/uuid.py
=> Make UUID compatible (Fixed issue #936)

graphene/tests/issues/test_956.py, graphene/types/enum.py
=> from_enum can now take a deprecation reason

docs/types/scalars.rst
=> Fix internal link on docs

docs/quickstart.rst
=> Fix wrong variable name

CODEOWNERS
Also removed @syrusakbary since he's not responding to pull requests.
=> Trying to get codeowners to work

setup.py
Closes #1008 
The only change should not affect graphene https://bitbucket.org/nielsenb/aniso8601/issues/24/float-induced-rounding-errors-when-parsing
=> Increased allowed version of aniso8601

docs/execution/fileuploading.rst, docs/execution/index.rst
=> Add file uploading docs

docs/types/objecttypes.rst
Fixes #1102
Most of this was already done in #1088 . This PR just cleans things up a bit and fixes another example.
=> Fix example code

examples/complex_example.py, examples/context_example.py, examples/simple_example.py, examples/starwars/schema.py, examples/starwars_relay/schema.py
Hello, following this changes
https://github.com/graphql-python/graphene/pull/969/files
https://github.com/graphql-python/graphene/issues/951
Examples should be fixed to be more clear as well.
=> Fixed examples, make root object explicit inside resolvers and mutate

graphene/types/tests/test_interface.py
This PR just adds some more tests around Interfaces to confirm some assumptions I had.
=> Add some more tests for Interface

docs/api/index.rst, docs/types/objecttypes.rst, graphene/types/field.py
=> Add note about the use of `args`

docs/quickstart.rst
=> Fix typo in quickstart document

graphene/types/base.py, graphene/types/enum.py, graphene/types/objecttype.py, graphene/types/tests/test_objecttype.py
This PR updates ObjectType to allow arguments to be passed to the metaclass.
=> ObjectType meta arguments

graphene/types/schema.py, graphene/types/tests/test_subscribe_async.py
=> Fix subscribe with arguments

docs/testing/index.rst
Updating docs with some fixes.
=> Language fixes on index.rst

.github/workflows/tests.yml, graphene/relay/connection.py, graphene/types/field.py, graphene/utils/crunch.py, graphene/utils/deduplicator.py, tox.ini
Recreation of #1345 (because I managed to mess up with git rebase)
=> Python 3.10 compatibility 

graphene/pyutils/version.py, graphene/relay/node.py, graphene/types/mutation.py, graphene/types/resolver.py, graphene/types/tests/test_subscribe_async.py, graphene/utils/module_loading.py, graphene/utils/tests/test_orderedtype.py, graphene/validation/tests/test_disable_introspection.py
I just refactor some functions, mostly was simple like:
- Swap if & else branches.
- Merge Else If Into Elif.
- De Morgan Identity.
=> Chore: Refactor Multi Expression Code ✨

.github/workflows/deploy.yml, .github/workflows/lint.yml
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-python/releases
=> Upgrade GitHub Actions

graphene/types/inputobjecttype.py, graphene/validation/depth_limit.py
Fixes MyPy errors causing all pipelines to fail after an upgrade of the mypy version.
=> fix: MyPy findings due to a mypy version upgrade were corrected

.github/workflows/tests.yml, docs/quickstart.rst, setup.py, tox.ini
Add Python 3.12 to CI and documentation
=> Python 3.12
